### ISSUE TITLE
Treehouse structure generation crash

### ISSUE THREAD

**Issue by kvverti** [robotbrain/luminiferous-uplands#16]
[crash-2019-08-01_21.45.53-server.txt](https://github.com/robotbrain/luminiferous-uplands/files/3459307/crash-2019-08-01_21.45.53-server.txt)

Relevant log:
```
[21:45:53] [Server-Worker-3/ERROR]: Requested chunk : -6 -2
[21:45:53] [Server-Worker-3/ERROR]: Region bounds : -23 -9 | -7 7
```

**Comment by kvverti** [comment]
```
---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 8/1/19 9:45 PM
Description: Feature placement

java.lang.RuntimeException: We are asking a region for a chunk out of bound | -6 -2
	at net.minecraft.world.ChunkRegion.getChunk(ChunkRegion.java:122)
	at net.minecraft.world.ViewableWorld.getChunk(ViewableWorld.java:106)
	at net.minecraft.world.ChunkRegion.getChunk(ChunkRegion.java:91)
	at net.minecraft.world.ChunkRegion.getBlockState(ChunkRegion.java:136)
	at robosky.ether.world.feature.minidungeons.TreehouseGenerator$Piece.generate(TreehouseGenerator.java:80)
	at net.minecraft.structure.StructureStart.generateStructure(StructureStart.java:66)
	at net.minecraft.world.gen.feature.StructureFeature.generate(StructureFeature.java:69)
	at net.minecraft.world.gen.feature.ConfiguredFeature.generate(ConfiguredFeature.java:36)
	at net.minecraft.world.gen.decorator.Decorator.method_15928(Decorator.java:85)
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:419)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at net.minecraft.world.gen.decorator.Decorator.generate(Decorator.java:84)
	at net.minecraft.world.gen.decorator.ConfiguredDecorator.generate(ConfiguredDecorator.java:35)
	at net.minecraft.world.gen.feature.DecoratedFeature.method_12892(DecoratedFeature.java:20)
	at net.minecraft.world.gen.feature.DecoratedFeature.generate(DecoratedFeature.java:13)
	at net.minecraft.world.gen.feature.ConfiguredFeature.generate(ConfiguredFeature.java:36)
	at net.minecraft.world.biome.Biome.generateFeatureStep(Biome.java:420)
	at net.minecraft.world.gen.chunk.ChunkGenerator.generateFeatures(ChunkGenerator.java:130)
	at net.minecraft.world.chunk.ChunkStatus.method_12151(ChunkStatus.java:83)
	at net.minecraft.world.chunk.ChunkStatus.runTask(ChunkStatus.java:217)
	at net.minecraft.server.world.ThreadedAnvilChunkStorage.method_17225(ThreadedAnvilChunkStorage.java:543)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at net.minecraft.server.world.ThreadedAnvilChunkStorage.method_17224(ThreadedAnvilChunkStorage.java:537)
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952)
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
	at net.minecraft.server.world.ChunkTaskPrioritySystem.method_17634(ChunkTaskPrioritySystem.java:58)
	at net.minecraft.util.MailboxProcessor.runNext(MailboxProcessor.java:83)
	at net.minecraft.util.MailboxProcessor.run(MailboxProcessor.java:123)
	at net.minecraft.util.MailboxProcessor.run(MailboxProcessor.java:91)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.world.ChunkRegion.getChunk(ChunkRegion.java:122)
	at net.minecraft.world.ViewableWorld.getChunk(ViewableWorld.java:106)
	at net.minecraft.world.ChunkRegion.getChunk(ChunkRegion.java:91)
	at net.minecraft.world.ChunkRegion.getBlockState(ChunkRegion.java:136)
	at robosky.ether.world.feature.minidungeons.TreehouseGenerator$Piece.generate(TreehouseGenerator.java:80)
	at net.minecraft.structure.StructureStart.generateStructure(StructureStart.java:66)
	at net.minecraft.world.gen.feature.StructureFeature.generate(StructureFeature.java:69)
	at net.minecraft.world.gen.feature.ConfiguredFeature.generate(ConfiguredFeature.java:36)
	at net.minecraft.world.gen.decorator.Decorator.method_15928(Decorator.java:85)
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:419)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at net.minecraft.world.gen.decorator.Decorator.generate(Decorator.java:84)
	at net.minecraft.world.gen.decorator.ConfiguredDecorator.generate(ConfiguredDecorator.java:35)
	at net.minecraft.world.gen.feature.DecoratedFeature.method_12892(DecoratedFeature.java:20)
	at net.minecraft.world.gen.feature.DecoratedFeature.generate(DecoratedFeature.java:13)
	at net.minecraft.world.gen.feature.ConfiguredFeature.generate(ConfiguredFeature.java:36)

-- Feature --
Details:
	Id: minecraft:decorated
	Description: < DecoratedFeature [minecraft:decorated] >
Stacktrace:
	at net.minecraft.world.biome.Biome.generateFeatureStep(Biome.java:420)

-- Generation --
Details:
	CenterX: -15
	CenterZ: -1
	Step: SURFACE_STRUCTURES
	Seed: -5849315727532977951
	Biome: luminiferous_uplands:ether_highlands
Stacktrace:
	at net.minecraft.world.gen.chunk.ChunkGenerator.generateFeatures(ChunkGenerator.java:130)
	at net.minecraft.world.chunk.ChunkStatus.method_12151(ChunkStatus.java:83)
	at net.minecraft.world.chunk.ChunkStatus.runTask(ChunkStatus.java:217)

-- Chunk to be generated --
Details:
	Location: -15,-1
	Position hash: -15
	Generator: robosky.ether.world.gen.EtherChunkGenerator@55c495bc
Stacktrace:
	at net.minecraft.server.world.ThreadedAnvilChunkStorage.method_17225(ThreadedAnvilChunkStorage.java:543)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at net.minecraft.server.world.ThreadedAnvilChunkStorage.method_17224(ThreadedAnvilChunkStorage.java:537)
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952)
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
	at net.minecraft.server.world.ChunkTaskPrioritySystem.method_17634(ChunkTaskPrioritySystem.java:58)
	at net.minecraft.util.MailboxProcessor.runNext(MailboxProcessor.java:83)
	at net.minecraft.util.MailboxProcessor.run(MailboxProcessor.java:123)
	at net.minecraft.util.MailboxProcessor.run(MailboxProcessor.java:91)

-- Affected level --
Details:
	All players: 1 total; [ServerPlayerEntity['Player446'/82, l='Autumn', x=-32.44, y=76.15, z=1.15]]
	Chunk stats: ServerChunkCache: 2014
	Level dimension: luminiferous_uplands:luminiferous_uplands
	Derived: true
	Level name: Autumn
	Level seed: -5737104586514096831
	Level generator: ID 01 - flat, ver 0. Features enabled: true
	Level generator options: {}
	Level spawn location: World: (224,4,16), Chunk: (at 0,0,0 in 14,1; contains blocks 224,0,16 to 239,255,31), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 1118 game time, 1118 day time
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 24912 (now: false), thunder time: 84649 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer.java:838)
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:774)
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:128)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:642)
	at java.lang.Thread.run(Thread.java:748)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Linux (amd64) version 4.18.0-25-generic
	Java Version: 1.8.0_212, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 692583440 bytes (660 MB) / 1557135360 bytes (1485 MB) up to 3704094720 bytes (3532 MB)
	CPUs: 8
	JVM Flags: 0 total; 
	Fabric Mods: 
		cloth: Cloth Events 0.3.1+build.23
		cloth-config2: Cloth Config v2 0.2.0
		fabric: Fabric API 0.3.0+build.207
		fabric-api-base: fabric-api-base 0.1.0+b494ebeb42
		fabric-biomes-v1: fabric-biomes-v1 0.1.0+896c7fbb42
		fabric-commands-v0: fabric-commands-v0 0.1.1+b494ebeb42
		fabric-containers-v0: fabric-containers-v0 0.1.2+b494ebeb42
		fabric-content-registries-v0: fabric-content-registries-v0 0.1.1+b494ebeb42
		fabric-crash-report-info-v1: fabric-crash-report-info-v1 0.1.0+5914746342
		fabric-events-interaction-v0: fabric-events-interaction-v0 0.1.0+ea100f6142
		fabric-events-lifecycle-v0: fabric-events-lifecycle-v0 0.1.0+5914746342
		fabric-item-groups-v0: fabric-item-groups-v0 0.1.0+1e69a0a542
		fabric-keybindings-v0: fabric-keybindings-v0 0.1.1+7dfef87c42
		fabric-language-scala: Fabric Language Scala 0.2.0.local
		fabric-loot-tables-v1: fabric-loot-tables-v1 0.1.0+b494ebeb42
		fabric-mining-levels-v0: fabric-mining-levels-v0 0.1.0+ab421b9c42
		fabric-models-v0: fabric-models-v0 0.1.0+5914746342
		fabric-networking-blockentity-v0: fabric-networking-blockentity-v0 0.1.1+b494ebeb42
		fabric-networking-v0: fabric-networking-v0 0.1.2+9b03381f42
		fabric-object-builders-v0: fabric-object-builders-v0 0.1.1+9b03381f42
		fabric-registry-sync-v0: fabric-registry-sync-v0 0.2.2+9b03381f42
		fabric-renderer-api-v1: fabric-renderer-api-v1 0.1.1+9b03381f42
		fabric-renderer-indigo: fabric-renderer-indigo 0.1.9+9b03381f42
		fabric-rendering-data-attachment-v1: fabric-rendering-data-attachment-v1 0.1.0+b494ebeb42
		fabric-rendering-fluids-v1: fabric-rendering-fluids-v1 0.1.0+dc4c57c242
		fabric-rendering-v0: fabric-rendering-v0 0.1.1+6dad974e42
		fabric-resource-loader-v0: fabric-resource-loader-v0 0.1.1+7495ea2842
		fabric-tag-extensions-v0: fabric-tag-extensions-v0 0.1.1+b494ebeb42
		fabric-textures-v0: fabric-textures-v0 0.1.4+b494ebeb42
		fabricloader: Fabric Loader 0.4.8+build.159
		jankson: Jankson 1.0.0+j1.1.2
		libgui: LibGui 1.2.3
		luminiferous_uplands: Luminiferous Uplands 1.0.0-alpha3
		modmenu: Mod Menu 1.5.4-85
		roughlyenoughitems: Roughly Enough Items 2.9.7+build.143
	Player Count: 1 / 8; [ServerPlayerEntity['Player446'/82, l='Autumn', x=-32.44, y=76.15, z=1.15]]
	Data Packs: vanilla, fabric/fabric-mining-levels-v0, fabric/luminiferous_uplands
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'
```

**Comment by kvverti** [comment]
Affects at least the autumn branch
